# Generated by Django 5.1.3 on 2025-01-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the candidate', max_length=255)),
                ('profile', models.TextField(help_text='Description or profile information of the candidate')),
                ('email', models.EmailField(help_text='Email address of the candidate', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the candidate', max_length=15, null=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated list of skills', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
